import React from 'react';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
	return (
		<html lang="en">
			<head>
				<style>{
					/*css*/ `
					html,
					body {
						margin: 0;
						font-family: sans-serif;
					}
				`
				}</style>
			</head>
			<body>{children}</body>
		</html>
	);
}
